### ISSUE TITLE
 ElasticSearchのヒープサイズの設定について

### ISSUE THREAD

**Issue by micci184** [MofuMofu2/TB2-ELKStack#14]
補足でヒープサイズの設定についても記載していいかなと思いましたー

## JVM heap size

ElasticSearchのヒープサイズは、以下で設定。

> /elasticsearch-5.2.2/config/jvm.options

Xms：初期ヒープサイズ
Xmx：最大ヒープサイズ

```bash

$ sudo vim jvm.options

 19 # Xms represents the initial size of total heap space
 20 # Xmx represents the maximum size of total heap space
 21
 22 -Xms2g
 23 -Xmx2g
```

最大ヒープサイズ(Xms)は、物理メモリの50%以下にする必要ありとのこと。
ただ、公式は古いのでちょっとアレですが。。

https://www.elastic.co/guide/en/elasticsearch/reference/master/heap-size.html

その結果、以下の表記にズレが生じている。。

***

-Xms2g

Set the minimum heap size to 2g.

***

**Comment by MofuMofu2** [comment]
@micci184 確かに最新版のURLにはheap-size記載が見当たりませんね…もうちょい探してみます。

**Comment by MofuMofu2** [comment]
#9 の内容と合わせて修正しているため、クローズします
