### ISSUE TITLE
ページ構成をRead.meに記述

### ISSUE THREAD

**Issue by MofuMofu2** [MofuMofu2/TB2-ELKStack#18]

**Comment by MofuMofu2** [comment]
@micci184 @hisas32 本の構成を書いてみましたがどうでしょう？わかりにくいところとかありますか？

**Comment by micci184** [comment]
@MofuMofu2 おぉ！いい感じ！GitHubの使い方については、Wikiでもいいかなーって思いましたー

**Comment by MofuMofu2** [comment]
確かに！第1版出したら拡張していきたいので、そのときに整備しますー
