### ISSUE TITLE
KibanaのダウンロードURLが記載されていない

### ISSUE THREAD

**Issue by micci184** [MofuMofu2/TB2-ELKStack#7]
* 2.6 zip ファイルを用いたインストール 
KibanaダウンロードURLを記載

**Comment by MofuMofu2** [comment]
https://github.com/MofuMofu2/TB2-ELKStack/commit/0cf6cd1aa26fc07399f4df462765870f6f613acc
#4 と合わせて対応しましたー。

**Comment by MofuMofu2** [comment]
URLを書いたのでクローズ
