### ISSUE TITLE
kibana.yml の編集

### ISSUE THREAD

**Issue by micci184** [MofuMofu2/TB2-ELKStack#8]
- [x] kibana.ymlのファイルパスを記載
/ELK-Stack/kibana-5.2.2-linux-x86_64/config/kibana.yml

- [x] kibana.ymlの編集する行番号を記載
20 # The URL of the Elasticsearch instance to use for all your queries.
21 #elasticsearch.url: "http://localhost:9200"

**Comment by MofuMofu2** [comment]
追記したのでクローズ
